//! The normalized event model — the system of record produced by adapters.
//!
//! Every field is copied verbatim from the source; none is generated by
//! Memscribe. This is the thin waist that decouples adapters from everything
//! downstream (whitepaper §4).

use serde::{Deserialize, Serialize};
use std::ops::Range;
use std::path::PathBuf;
use time::OffsetDateTime;

/// The current event schema version. Bumped on any breaking change to
/// [`CaptureEvent`] / [`EventKind`]. Consumers gate on this independently of the
/// crate's semver.
pub const SCHEMA_VERSION: u16 = 1;

/// An RFC3339 timestamp copied verbatim from the source.
pub type Timestamp = OffsetDateTime;

/// A stable blake3 content hash, hex-encoded — used as an `event_id` fallback
/// when a tool provides no native id, and to derive deterministic episode ids.
#[must_use]
pub fn content_id(bytes: &[u8]) -> String {
    blake3::hash(bytes).to_hex().to_string()
}

/// Which tool produced an event.
#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum SourceKind {
    /// Anthropic Claude Code.
    ClaudeCode,
    /// OpenAI Codex CLI.
    Codex,
    /// Google Gemini CLI.
    Gemini,
    /// Any OpenTelemetry GenAI-instrumented agent.
    Otel,
    /// Cursor (VS Code fork).
    Cursor,
    /// Windsurf (Codeium).
    Windsurf,
    /// Zed editor agent.
    Zed,
    /// VS Code (Copilot Chat / chat sessions).
    VsCode,
    /// GitHub Copilot.
    Copilot,
    /// Source could not be determined.
    Unknown,
}

impl SourceKind {
    /// The stable snake_case identifier (matches serde and CLI `--as` values).
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            SourceKind::ClaudeCode => "claude_code",
            SourceKind::Codex => "codex",
            SourceKind::Gemini => "gemini",
            SourceKind::Otel => "otel",
            SourceKind::Cursor => "cursor",
            SourceKind::Windsurf => "windsurf",
            SourceKind::Zed => "zed",
            SourceKind::VsCode => "vscode",
            SourceKind::Copilot => "copilot",
            SourceKind::Unknown => "unknown",
        }
    }

    /// Parse a `SourceKind` from a CLI/`--as` identifier (tolerant of aliases).
    #[must_use]
    pub fn parse(s: &str) -> Option<SourceKind> {
        match s.trim().to_ascii_lowercase().as_str() {
            "claude_code" | "claude" | "claude-code" => Some(SourceKind::ClaudeCode),
            "codex" => Some(SourceKind::Codex),
            "gemini" => Some(SourceKind::Gemini),
            "otel" | "opentelemetry" => Some(SourceKind::Otel),
            "cursor" => Some(SourceKind::Cursor),
            "windsurf" => Some(SourceKind::Windsurf),
            "zed" => Some(SourceKind::Zed),
            "vscode" | "vs_code" | "vs-code" | "code" => Some(SourceKind::VsCode),
            "copilot" | "github_copilot" => Some(SourceKind::Copilot),
            "unknown" => Some(SourceKind::Unknown),
            _ => None,
        }
    }
}

impl std::fmt::Display for SourceKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A git reference captured at session start: commit sha and (optional) branch.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct GitRef {
    /// The commit sha at the time of capture.
    pub sha: String,
    /// The branch name, if known.
    pub branch: Option<String>,
}

/// The project a session is bound to (captured at session start).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ProjectRef {
    /// The working directory the agent ran in.
    pub cwd: PathBuf,
    /// The repository root, if resolved.
    pub repo_root: Option<PathBuf>,
    /// The git ref at session start, if any.
    pub git: Option<GitRef>,
}

impl ProjectRef {
    /// A minimal project ref for a bare working directory.
    #[must_use]
    pub fn from_cwd(cwd: impl Into<PathBuf>) -> Self {
        ProjectRef {
            cwd: cwd.into(),
            repo_root: None,
            git: None,
        }
    }
}

/// A pointer back into the source bytes, for replay and audit.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct SourceLocation {
    /// The transcript file the record came from.
    pub file: PathBuf,
    /// Byte offset of the record's start within the file.
    pub byte_offset: u64,
    /// 1-based line number of the record within the file.
    pub line_no: u64,
}

impl SourceLocation {
    /// Construct a source location.
    #[must_use]
    pub fn new(file: impl Into<PathBuf>, byte_offset: u64, line_no: u64) -> Self {
        SourceLocation {
            file: file.into(),
            byte_offset,
            line_no,
        }
    }
}

impl std::fmt::Display for SourceLocation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}:{}@{}",
            self.file.display(),
            self.line_no,
            self.byte_offset
        )
    }
}

/// A content part within a turn. Multimodal- and version-tolerant: anything
/// unrecognized is preserved verbatim as [`Part::Other`].
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(tag = "part", rename_all = "snake_case")]
pub enum Part {
    /// Plain text content.
    Text {
        /// The verbatim text.
        text: String,
    },
    /// Model-private reasoning, where the tool exposes it.
    Thinking {
        /// The verbatim thinking text.
        text: String,
    },
    /// A tool invocation embedded in the turn.
    ToolUse {
        /// The tool-native call id.
        call_id: String,
        /// The tool name.
        name: String,
        /// The raw arguments.
        args: serde_json::Value,
    },
    /// A tool result embedded in the turn.
    ToolResult {
        /// The tool-native call id this result answers.
        call_id: String,
        /// The raw output.
        output: serde_json::Value,
    },
    /// An image/attachment reference (content not captured).
    Image {
        /// The media type, if known.
        media_type: Option<String>,
    },
    /// Any unrecognized part, preserved verbatim.
    Other {
        /// The raw JSON of the part.
        raw: serde_json::Value,
    },
}

/// Token usage for an assistant turn, where the tool reports it.
#[derive(Clone, Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct Usage {
    /// Input/prompt tokens.
    pub input_tokens: Option<u64>,
    /// Output/completion tokens.
    pub output_tokens: Option<u64>,
    /// Cache-read tokens.
    pub cache_read_tokens: Option<u64>,
    /// Cache-creation tokens.
    pub cache_creation_tokens: Option<u64>,
}

/// A normalized file edit. The diff is copied from the source when available,
/// or computed deterministically (e.g. via `similar`) when only old/new are
/// present.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct Diff {
    /// The path that was edited.
    pub path: PathBuf,
    /// The prior contents, if the source provides them.
    pub old: Option<String>,
    /// The new contents, if the source provides them.
    pub new: Option<String>,
    /// Unified-diff text — from the source, or computed deterministically.
    pub unified: Option<String>,
    /// Count of added lines.
    pub added_lines: u32,
    /// Count of removed lines.
    pub removed_lines: u32,
}

impl Diff {
    /// A minimal diff for a path with no captured content.
    #[must_use]
    pub fn for_path(path: impl Into<PathBuf>) -> Self {
        Diff {
            path: path.into(),
            old: None,
            new: None,
            unified: None,
            added_lines: 0,
            removed_lines: 0,
        }
    }
}

/// The kind of a normalized event. [`EventKind::Unknown`] is load-bearing: an
/// unrecognized record type or new field is preserved verbatim and flagged,
/// never discarded — this is how the stream stays lossless across tool-version
/// churn (whitepaper §4).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(tag = "event", rename_all = "snake_case")]
pub enum EventKind {
    /// The session opened: cwd, git, model, tool version.
    SessionStart {
        /// Working directory.
        cwd: PathBuf,
        /// Git ref at session start.
        git: Option<GitRef>,
        /// The model in use, if reported.
        model: Option<String>,
        /// The tool version, if reported.
        tool_version: Option<String>,
    },
    /// A user message.
    UserTurn {
        /// The flattened text of the turn.
        text: String,
        /// The structured parts, if any.
        #[serde(default)]
        parts: Vec<Part>,
    },
    /// An assistant message.
    AssistantTurn {
        /// The flattened text of the turn.
        text: String,
        /// Model-private reasoning, if exposed.
        thinking: Option<String>,
        /// The model that produced the turn.
        model: Option<String>,
        /// Token usage, if reported.
        usage: Option<Usage>,
        /// The structured parts, if any.
        #[serde(default)]
        parts: Vec<Part>,
    },
    /// A tool call.
    ToolCall {
        /// The tool-native call id.
        call_id: String,
        /// The tool name.
        name: String,
        /// The raw arguments.
        args: serde_json::Value,
    },
    /// A tool result.
    ToolResult {
        /// The call id this result answers.
        call_id: String,
        /// Whether the tool succeeded.
        ok: bool,
        /// The raw output.
        output: serde_json::Value,
    },
    /// A file edit, normalized from Edit/Write/apply_patch/replace.
    FileEdit {
        /// The originating tool call id, if any.
        call_id: Option<String>,
        /// The normalized diff.
        diff: Diff,
    },
    /// Model-side history compaction — flagged, never stored as truth.
    Compaction {
        /// The (inclusive-start, exclusive-end) seq range that was replaced.
        replaced: Range<u64>,
    },
    /// A user rewind — logical truncation back to an earlier event.
    Rewind {
        /// The event id rewound to.
        to_event: String,
    },
    /// The session ended.
    SessionEnd {
        /// The reason, if reported.
        reason: Option<String>,
    },
    /// Forward-compat: an unrecognized record, preserved verbatim and flagged.
    Unknown {
        /// The raw record type string, if any.
        raw_type: String,
        /// The full raw record.
        raw: serde_json::Value,
    },
}

impl EventKind {
    /// A stable tag string for the variant — used in dedup keys and tests.
    #[must_use]
    pub fn tag(&self) -> &'static str {
        match self {
            EventKind::SessionStart { .. } => "session_start",
            EventKind::UserTurn { .. } => "user_turn",
            EventKind::AssistantTurn { .. } => "assistant_turn",
            EventKind::ToolCall { .. } => "tool_call",
            EventKind::ToolResult { .. } => "tool_result",
            EventKind::FileEdit { .. } => "file_edit",
            EventKind::Compaction { .. } => "compaction",
            EventKind::Rewind { .. } => "rewind",
            EventKind::SessionEnd { .. } => "session_end",
            EventKind::Unknown { .. } => "unknown",
        }
    }
}

/// A normalized capture event. Stable, versioned (`schema_version`) public
/// contract (whitepaper §4).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct CaptureEvent {
    /// The event schema version (see [`SCHEMA_VERSION`]).
    pub schema_version: u16,
    /// Which tool produced the event.
    pub source: SourceKind,
    /// The tool-native session/thread id.
    pub session_id: String,
    /// Monotonic per-session sequence, assigned from file order.
    pub seq: u64,
    /// Tool-native id (e.g. a Claude Code uuid), or a `blake3(content)` fallback.
    pub event_id: String,
    /// DAG link where the tool provides one (e.g. Claude Code `parentUuid`).
    pub parent_id: Option<String>,
    /// RFC3339 timestamp from the source.
    #[serde(with = "time::serde::rfc3339")]
    pub timestamp: OffsetDateTime,
    /// The project binding captured at session start.
    pub project: ProjectRef,
    /// The event payload.
    pub kind: EventKind,
    /// Pointer back into the source bytes, for replay and audit.
    pub provenance: SourceLocation,
}

impl CaptureEvent {
    /// A dedup key: tool-native `event_id` is authoritative within a session.
    #[must_use]
    pub fn dedup_key(&self) -> (&str, &str) {
        (self.session_id.as_str(), self.event_id.as_str())
    }
}
